# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Twiddler
version:      0.0.1
version_from: lib/Text/Twiddler.pm
installdirs:  site
requires:
    Class::Std:                    0
    Class::Std::Utils:             0
    List::Cycle:                   0
    Locale::Maketext::Pseudo:      0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
